import Head from 'next/head';
import { useThemeEffect } from '@/lib/hooks/useThemeEffect';
import { useToggleTheme } from '@/lib/hooks/useToggleTheme';

export default function Home() {
  const [nowTheme, toggleTheme] = useToggleTheme();
  useThemeEffect();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello, Asside</h1>
        <button onClick={toggleTheme}>다크모드</button>
      </main>
    </>
  );
}
