import Head from 'next/head';
import AuthForm from '@/components/auth/AuthForm';
import BasicLayout from '@/components/layouts/BasicLayout';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useCallback, useEffect, useState } from 'react';
import { logIn } from '@/lib/apis/auth';
import { useRouter } from 'next/router';
import { SignUpParams } from '@/lib/apis/types';
import { GetServerSideProps } from 'next';

function Login() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [loginError, setLoginError] = useState<string>('');

  const { isLoading, mutate } = useMutation({
    mutationFn: logIn,
    onMutate: () => {
      setLoginError('');
    },
    onSuccess: () => {
      queryClient.refetchQueries(['me']);
      router.push('/');
    },
    onError: (e: any) => {
      const error = e.response?.data;
      setLoginError(error.name);
    },
  });

  const onSubmit = useCallback(
    async ({ email, password }: SignUpParams) => {
      if (!email || !password) return;
      console.log(email, password);
      mutate({ email, password });
    },
    [mutate],
  );

  return (
    <>
      <Head>
        <title>로그인 - Asside</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout header="onlyBack">
        <AuthForm
          mode="login"
          onSubmit={onSubmit}
          isLoading={isLoading}
          serverError={loginError}
        />
      </BasicLayout>
    </>
  );
}

export default Login;
