import Head from 'next/head';
import AuthForm from '@/components/auth/AuthForm';
import BasicLayout from '@/components/layouts/BasicLayout';
import { useMutation } from '@tanstack/react-query';
import { useCallback, useState } from 'react';
import { signUp } from '@/lib/apis/auth';
import { SignUpParams } from '@/lib/apis/types';
import { GetServerSideProps } from 'next';

function SignUp() {
  const [isSignedUp, setIsSignedUp] = useState<boolean>(false);
  const [signUpError, setSignUpError] = useState<string>('');

  const { isLoading, mutate } = useMutation({
    mutationFn: signUp,
    onMutate: () => {
      setSignUpError('');
    },
    onSuccess: () => {
      setIsSignedUp(true);
    },
    onError: (e: any) => {
      const error = e.response?.data;
      if (error.payload) {
        if (error.payload === 'email') {
          setSignUpError(`EmailExistsError`);
          return;
        }
        if (error.payload === 'username') {
          setSignUpError('UsernameExistsError');
          return;
        }
      }
      setSignUpError(error.name);
    },
  });

  const onSubmit = useCallback(
    async ({ email, password, username }: SignUpParams) => {
      if (!email || !password || !username) return;
      mutate({ email, username, password });
    },
    [mutate],
  );

  return (
    <>
      <Head>
        <title>로그인 - Asside</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout header="onlyBack">
        <AuthForm
          mode="signup"
          onSubmit={onSubmit}
          isLoading={isLoading}
          serverError={signUpError}
          isSignedUp={isSignedUp}
          setIsSignedUp={setIsSignedUp}
        />
      </BasicLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const { cookies } = req;
  if (cookies.access_token) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }
  return {
    props: {},
  };
};

export default SignUp;
